# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [7]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key
g_key

'AIzaSyC1J2RUNsaTmsAzyImXudV5OX00uz90Bb8'

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [8]:
df = pd.read_csv('../my_output_data/city_info.csv')
df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Goiás,-15.58,-49.64,104.09,9,0,8.23,BR,1601826036
1,Luckenwalde,52.08,13.17,64.00,52,18,5.01,DE,1601826036
2,Mount Isa,-20.73,139.50,68.00,45,0,10.63,AU,1601826037
3,Sandown,50.65,-1.16,54.00,94,100,5.99,GB,1601826037
4,Hamada,34.88,132.08,71.01,36,83,10.58,JP,1601826037
...,...,...,...,...,...,...,...,...,...
595,Ad Dindar,13.20,34.17,81.90,62,35,8.05,SD,1601826116
596,Tampico,22.22,-97.85,78.80,78,40,6.93,MX,1601825988
597,Montería,8.75,-75.88,78.53,86,100,7.70,CO,1601826075
598,Guariba,-21.36,-48.23,96.80,28,64,4.70,BR,1601826117
599,Hedaru,-4.50,37.90,78.69,47,84,7.85,TZ,1601826117

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
!jupyter nbextension enable --py gmaps

Enabling notebook extension jupyter-gmaps/extension...
      - Validating: ok

In [46]:
# Access maps with unique API key
gmaps.configure(api_key=g_key)
figure_layout = {
    'width': '800px',
    'height': '600px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
coordinates=[]
hums = []
for index, row in df.iterrows():
    lat = row['Lat']
    lng = row['Lng']
    hum = row['Humidity']
    coordinate = (lat,lng)
    coordinates.append(coordinate)
    hums.append(hum)
coordinates
# markers = gmaps.marker_layer(coordinates)
fig = gmaps.figure(layout=figure_layout)
heatmap = gmaps.heatmap_layer(coordinates,weights=hums,dissipating=True)
fig.add_layer(heatmap)
fig

Figure(layout=FigureLayout(border='1px solid black', height='600px', margin='0 auto 0 auto', padding='1px', wi…

In [48]:
fig.savefig('../my_images/hum_heatmap.png')

AttributeError: 'Figure' object has no attribute 'savefig'

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [47]:
df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Goiás,-15.58,-49.64,104.09,9,0,8.23,BR,1601826036
1,Luckenwalde,52.08,13.17,64.00,52,18,5.01,DE,1601826036
2,Mount Isa,-20.73,139.50,68.00,45,0,10.63,AU,1601826037
3,Sandown,50.65,-1.16,54.00,94,100,5.99,GB,1601826037
4,Hamada,34.88,132.08,71.01,36,83,10.58,JP,1601826037
...,...,...,...,...,...,...,...,...,...
595,Ad Dindar,13.20,34.17,81.90,62,35,8.05,SD,1601826116
596,Tampico,22.22,-97.85,78.80,78,40,6.93,MX,1601825988
597,Montería,8.75,-75.88,78.53,86,100,7.70,CO,1601826075
598,Guariba,-21.36,-48.23,96.80,28,64,4.70,BR,1601826117
599,Hedaru,-4.50,37.90,78.69,47,84,7.85,TZ,1601826117

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure